export const SYMBOL_SELECTED = "SYMBOL_SELECTED";
export const PERIOD_SELECTED = "PERIOD_SELECTED";
export const FETCH_PRICES = "FETCH_PRICES";
export const PRICES_FETCHED = "PRICES_FETCHED";
export const FETCH_PRICES_FAILED = "FETCH_PRICES_FAILED";
export const SEARCH_SYMBOL = "SEARCH_SYMBOL";
export const SEARCH_SYMBOL_FAILED = "SEARCH_SYMBOL_FAILED";
export const SYMBOL_FOUND = "SYMBOL_FOUND";
